name: Deploy to QA
on:
  push:
    branches:
      - development
jobs:
  deploy:
    name: Deploy Code to QA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npm run build --if-present
        env:
          CI: true
      - run: npm run sync-data
        env:
          GOOGLE_API_CREDS: ${{ secrets.GOOGLE_API_CREDS }}
      - run: cp -R tmp/data build/data
      - run: npm run ssr
      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GOOGLE_API_CREDS }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true
      - name: Sync GCP Storage Bucket
        run: |-
          gsutil -h "Cache-Control:no-store" -m rsync -r -c build/ gs://$GCS_BUCKET_QA
        env:
          GCS_BUCKET_QA: ${{ secrets.GCS_BUCKET_QA }}
